// KasSigner — Air-gapped offline signing device for Kaspa
// Copyright (C) 2025-2026 KasSigner Project (kassigner@proton.me)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


// hw/camera.rs — GC0308 camera sensor driver for M5Stack CoreS3
// 100% Rust, no-std, no-alloc
//
// Hardware: GC0308 0.3MP camera (640x480 max)
//   - DVP 8-bit parallel interface via LCD_CAM peripheral
//   - SCCB (I2C) control at address 0x21
//   - XCLK generated by ESP32-S3 LEDC on GPIO2
//   - Camera reset via AW9523B IO expander P1_0
//
// CoreS3 Pin Map:
//   PCLK  = GPIO45     VSYNC = GPIO46     HREF = GPIO38
//   D0    = GPIO39      D1   = GPIO40      D2  = GPIO41
//   D3    = GPIO42      D4   = GPIO15      D5  = GPIO16
//   D6    = GPIO48      D7   = GPIO47
//   SCCB SDA = GPIO12 (shared I2C bus)
//   SCCB SCL = GPIO11 (shared I2C bus)
//
// Init: Espressif gc0308_sensor_default_regs + subsample QVGA via Page 1 regs
// Capture: Stock esp-hal Camera::receive()/wait() API, DMA to SRAM

use crate::log;
use esp_hal::delay::Delay;

/// GC0308 I2C/SCCB address (7-bit)
const GC0308_ADDR: u8 = 0x21;

/// GC0308 chip ID expected value
const GC0308_CHIP_ID: u8 = 0x9B;

// ═══════════════════════════════════════════════════════════════
// GC0308 Register Definitions
// ═══════════════════════════════════════════════════════════════

// Page select register (0xfe: 0x00=page0, 0x01=page1)
const REG_PAGE_SELECT: u8 = 0xfe;

// Page 0 registers (only those used in code)
const REG_CHIP_ID: u8 = 0x00;
const REG_OUTPUT_FORMAT: u8 = 0x24;
const REG_OUTPUT_EN: u8 = 0x25;

// ═══════════════════════════════════════════════════════════════
// GC0308 Default Register Table
// ═══════════════════════════════════════════════════════════════
// Derived from espressif/esp32-camera gc0308.c defaults.
// Format: [register, value] pairs. Page 0 unless noted.

static GC0308_DEFAULTS: &[(u8, u8)] = &[
    // Espressif gc0308_sensor_default_regs table
    // from espressif/esp32-camera (sensors/private_include/gc0308_settings.h)
    // Uses subsample mode (Page 1 regs 0x53-0x59) for clean QVGA output.

    (0xfe, 0x80), // Soft reset
    // (delay 20ms inserted by code)
    (0xfe, 0x00), // Select page 0

    // === Espressif default register table — Page 0 ===
    (0xec, 0x20),
    (0x05, 0x00), // ROW_START_H
    (0x06, 0x00), // ROW_START_L
    (0x07, 0x00), // COL_START_H
    (0x08, 0x00), // COL_START_L
    (0x09, 0x01), // WIN_HEIGHT_H  (488 = 0x01E8)
    (0x0a, 0xe8), // WIN_HEIGHT_L
    (0x0b, 0x02), // WIN_WIDTH_H   (648 = 0x0288)
    (0x0c, 0x88), // WIN_WIDTH_L
    (0x0d, 0x02), // VS_ST
    (0x0e, 0x02), // VS_ET
    (0x10, 0x26), // RSH_WIDTH
    (0x11, 0x0d), // TSP_WIDTH
    (0x12, 0x2a), // SAMPLE_HOLD_DELAY
    (0x13, 0x00), // ROW_TAIL_WIDTH
    (0x14, 0x10), // CISCTL_MODE1 (no mirror/flip)
    (0x15, 0x0a), // CISCTL_MODE2: progressive VGA, NO even-skip
    (0x16, 0x05), // CISCTL_MODE3
    (0x17, 0x01), // CISCTL_MODE4
    (0x18, 0x44), // Analog timing
    (0x19, 0x44), // Analog timing
    (0x1a, 0x2a), // ANALOG_MODE1
    (0x1b, 0x00), // ANALOG_MODE2
    (0x1c, 0x49), // HRST_RSG_V18
    (0x1d, 0x9a), // VREF_V25
    (0x1e, 0x61), // ADC_R
    (0x1f, 0x00), // PAD_DRV (<=24MHz, 0x00 is OK per Espressif)
    (0x20, 0x7f), // BLOCK_EN1
    (0x21, 0xfa), // BLOCK_EN2
    (0x22, 0x57), // AAAA_EN: AEC+AGC+AWB enabled
    (0x24, 0x91), // Output format: Y-only, ISP high 8 bits
    (0x25, 0x0f), // Output enable
    (0x26, 0x03), // Sync mode
    (0x28, 0x00), // PCLK_DIV: no division (ESP32-S3 supports up to 40MHz)
    (0x2d, 0x0a),
    (0x2f, 0x01),
    (0x30, 0xf7), // BLK mode
    (0x31, 0x50), // BLK limit
    (0x32, 0x00), // Global offset
    (0x33, 0x28),
    (0x34, 0x2a),
    (0x35, 0x28),
    (0x39, 0x04), // BLK config
    (0x3a, 0x20), // R offset
    (0x3b, 0x20), // G offset
    (0x3c, 0x00), // B offset
    (0x3d, 0x00), // G2 offset
    (0x3e, 0x00),
    (0x3f, 0x00),

    // Pre-gain
    (0x50, 0x14), // GLOBAL_GAIN
    (0x52, 0x41),
    (0x53, 0x80),
    (0x54, 0x80),
    (0x55, 0x80),
    (0x56, 0x80),

    // AWB gains
    (0x5a, 0x56), // AWB_R_GAIN
    (0x5b, 0x40), // AWB_G_GAIN
    (0x5c, 0x4a), // AWB_B_GAIN

    // AEC weights
    (0x8b, 0x20),
    (0x8c, 0x20),
    (0x8d, 0x20),
    (0x8e, 0x14),
    (0x8f, 0x10),
    (0x90, 0x14),
    (0x91, 0x3c),
    (0x92, 0x50),

    // LSC (Lens Shading)
    (0x5d, 0x12),
    (0x5e, 0x1a),
    (0x5f, 0x24),

    // DNDD (Denoise)
    (0x60, 0x07),
    (0x61, 0x15),
    (0x62, 0x08),
    (0x64, 0x03),
    (0x66, 0xe8),
    (0x67, 0x86),
    (0x68, 0x82),

    // ASDE
    (0x69, 0x18),
    (0x6a, 0x0f),
    (0x6b, 0x00),
    (0x6c, 0x5f),
    (0x6d, 0x8f),
    (0x6e, 0x55),
    (0x6f, 0x38),
    (0x70, 0x15),
    (0x71, 0x33),

    // INTPEE (Edge Enhancement) — boosted for sharper QR/BB edges
    (0x72, 0xfe), // stronger edge enhance (was 0xdc)
    (0x73, 0x00),
    (0x74, 0x02),
    (0x75, 0x3f),
    (0x76, 0x02),
    (0x77, 0x38),
    (0x78, 0x88),
    (0x79, 0x81),
    (0x7a, 0x81),
    (0x7b, 0x22),
    (0x7c, 0xff),

    // Gamma / Color matrix
    (0x93, 0x48),
    (0x94, 0x02),
    (0x95, 0x07),
    (0x96, 0xe0),
    (0x97, 0x40),
    (0x98, 0xf0),

    // Saturation + Contrast
    (0xb1, 0x40), // Cb saturation
    (0xb2, 0x40), // Cr saturation
    (0xb3, 0x50), // Contrast 1.25x (was 0x40=1.0x) — wider QR black/white gap
    (0xb6, 0xe0),

    // More ISP
    (0xbd, 0x38),
    (0xbe, 0x36),

    // AEC registers
    (0xd0, 0xCB),
    (0xd1, 0x10),
    (0xd2, 0x90),
    (0xd3, 0x38), // AEC target Y (lowered from 0x48 for Y-only mode)
    (0xd5, 0xF2),
    (0xd6, 0x16),
    (0xdb, 0x92),
    (0xdc, 0xA5),
    (0xdf, 0x23),
    (0xd9, 0x00),
    (0xda, 0x00),
    (0xe0, 0x09),
    (0xed, 0x04),
    (0xee, 0xa0),
    (0xef, 0x40),
    (0x80, 0x03),

    // Gamma curve
    (0x9F, 0x10),
    (0xA0, 0x20),
    (0xA1, 0x38),
    (0xA2, 0x4e),
    (0xA3, 0x63),
    (0xA4, 0x76),
    (0xA5, 0x87),
    (0xA6, 0xa2),
    (0xA7, 0xb8),
    (0xA8, 0xca),
    (0xA9, 0xd8),
    (0xAA, 0xe3),
    (0xAB, 0xeb),
    (0xAC, 0xf0),
    (0xAD, 0xF8),
    (0xAE, 0xFD),
    (0xAF, 0xFF),

    // Second gamma/Y curve
    (0xc0, 0x00),
    (0xc1, 0x10),
    (0xc2, 0x1c),
    (0xc3, 0x30),
    (0xc4, 0x43),
    (0xc5, 0x54),
    (0xc6, 0x65),
    (0xc7, 0x75),
    (0xc8, 0x93),
    (0xc9, 0xB0),
    (0xca, 0xCB),
    (0xcb, 0xE6),
    (0xcc, 0xFF),

    // Clock / PLL
    (0xf0, 0x02),
    (0xf1, 0x01),
    (0xf2, 0x02),
    (0xf3, 0x30),
    (0xf7, 0x04),
    (0xf8, 0x02),
    (0xf9, 0x9f),
    (0xfa, 0x78),

    // === Page 1: AWB / AEC measure window / misc ===
    (0xfe, 0x01),
    (0x00, 0xf5),
    (0x02, 0x20),
    (0x04, 0x10),
    (0x05, 0x08),
    (0x06, 0x20),
    (0x08, 0x0a),
    (0x0a, 0xa0),
    (0x0b, 0x60),
    (0x0c, 0x08),
    (0x0e, 0x44),
    (0x0f, 0x32),
    (0x10, 0x41),
    (0x11, 0x37),
    (0x12, 0x22),
    (0x13, 0x19),
    (0x14, 0x44),
    (0x15, 0x44),
    (0x16, 0xc2),
    (0x17, 0xA8),
    (0x18, 0x18),
    (0x19, 0x50),
    (0x1a, 0xd8),
    (0x1b, 0xf5),
    (0x70, 0x40),
    (0x71, 0x58),
    (0x72, 0x30),
    (0x73, 0x48),
    (0x74, 0x20),
    (0x75, 0x60),
    (0x77, 0x20),
    (0x78, 0x32),
    (0x30, 0x03),
    (0x31, 0x40),
    (0x32, 0x10),
    (0x33, 0xe0),
    (0x34, 0xe0),
    (0x35, 0x00),
    (0x36, 0x80),
    (0x37, 0x00),
    (0x38, 0x04),
    (0x39, 0x09),
    (0x3a, 0x12),
    (0x3b, 0x1C),
    (0x3c, 0x28),
    (0x3d, 0x31),
    (0x3e, 0x44),
    (0x3f, 0x57),
    (0x40, 0x6C),
    (0x41, 0x81),
    (0x42, 0x94),
    (0x43, 0xA7),
    (0x44, 0xB8),
    (0x45, 0xD6),
    (0x46, 0xEE),
    (0x47, 0x0d),
    (0x62, 0xf7),
    (0x63, 0x68),
    (0x64, 0xd3),
    (0x65, 0xd3),
    (0x66, 0x60),

    // Back to Page 0 for frame timing
    (0xfe, 0x00),
    (0x01, 0x32), // HBLANK
    (0x02, 0x0c), // VBLANK
    (0x0f, 0x01), // VB_HB
    (0xe2, 0x00),
    (0xe3, 0x78),
    (0xe4, 0x00),
    (0xe5, 0xfe),
    (0xe6, 0x01),
    (0xe7, 0xe0),
    (0xe8, 0x01),
    (0xe9, 0xe0),
    (0xea, 0x01),
    (0xeb, 0xe0),
    (0xfe, 0x00),
];

/// Subsample mode register writes for QVGA (320×240) output.
/// Applied AFTER GC0308_DEFAULTS. Mirrors Espressif's set_framesize() logic.
///
/// The GC0308's internal digital subsample engine (Page 1, regs 0x53-0x59)
/// processes the full VGA image internally and outputs clean 320×240 with
/// proper HREF timing — no marker byte artifacts.
///
/// Ratio 1/2: subsample_cfgs[3] = {210, 420, 0x22, 0x00, 0x00, 0x00, 0x00}
/// Window: full VGA (row_start=0, col_start=0, win=488×648)
static GC0308_SUBSAMPLE_QVGA: &[(u8, u8)] = &[
    // Ensure Page 0
    (0xfe, 0x00),

    // Window covers full sensor (subsample block reduces output)
    (0x05, 0x00), // ROW_START_H = 0
    (0x06, 0x00), // ROW_START_L = 0
    (0x07, 0x00), // COL_START_H = 0
    (0x08, 0x00), // COL_START_L = 0
    (0x09, 0x01), // WIN_HEIGHT_H  (488 = 0x01E8)
    (0x0a, 0xe8), // WIN_HEIGHT_L
    (0x0b, 0x02), // WIN_WIDTH_H   (648 = 0x0288)
    (0x0c, 0x88), // WIN_WIDTH_L

    // Disable crop mode — subsample handles size reduction
    (0x46, 0x00),

    // Switch to Page 1 for subsample registers
    (0xfe, 0x01),

    // Subsample mode: 1/2 ratio in both H and V
    (0x54, 0x22), // SUBSAMPLE_MODE
    (0x56, 0x00), // Y subsample config 0
    (0x57, 0x00), // Y subsample config 1
    (0x58, 0x00), // UV subsample config 0
    (0x59, 0x00), // UV subsample config 1

    // Back to Page 0
    (0xfe, 0x00),
];

// ═══════════════════════════════════════════════════════════════
// SCCB (I2C) Register Access
// ═══════════════════════════════════════════════════════════════

/// Write a single register via I2C/SCCB
pub fn sccb_write<I2C: embedded_hal::i2c::I2c>(i2c: &mut I2C, reg: u8, val: u8) -> bool {
    i2c.write(GC0308_ADDR, &[reg, val]).is_ok()
}

/// Read a single register via I2C/SCCB
fn sccb_read<I2C: embedded_hal::i2c::I2c>(i2c: &mut I2C, reg: u8) -> Option<u8> {
    let mut buf = [0u8; 1];
    if i2c.write(GC0308_ADDR, &[reg]).is_ok()
        && i2c.read(GC0308_ADDR, &mut buf).is_ok()
    {
        return Some(buf[0]);
    }
    None
}

// ═══════════════════════════════════════════════════════════════
// Camera Reset (via AW9523B IO Expander)
// ═══════════════════════════════════════════════════════════════
/// Full camera power-on sequence via AW9523B IO expander
/// Schematic pin map:
///   P0.4 = CAM_PWDN (active HIGH = power down, LOW = active)
///   P1.0 = CAM_RST  (active LOW = reset, HIGH = normal)
///
/// Full camera power-on sequence via AW9523B IO expander
pub fn camera_power_on<I2C: embedded_hal::i2c::I2c>(i2c: &mut I2C, delay: &mut Delay) {
    // Verify AW9523B is responding
    let mut chip_id = [0u8; 1];
    let aw_ok = i2c.write_read(0x58u8, &[0x10u8], &mut chip_id).is_ok();
    log!("   AW9523B chip_id=0x{:02x} (expect 0x23) ok={}", chip_id[0], aw_ok);

    // Read current direction registers to verify they're configured as outputs
    let mut dir_p0 = [0u8; 1];
    let mut dir_p1 = [0u8; 1];
    let _ = i2c.write_read(0x58u8, &[0x04u8], &mut dir_p0);
    let _ = i2c.write_read(0x58u8, &[0x05u8], &mut dir_p1);
    log!("   Direction P0=0x{:02x} P1=0x{:02x} (expect 0x00=all outputs)", dir_p0[0], dir_p1[0]);

    // If directions not set, force them
    if dir_p0[0] != 0x00 {
        log!("   FIXING P0 direction → outputs");
        let _ = i2c.write(0x58u8, &[0x12u8, 0xFFu8]); // LED mode = GPIO
        let _ = i2c.write(0x58u8, &[0x04u8, 0x00u8]); // Direction = output
    }
    if dir_p1[0] != 0x00 {
        log!("   FIXING P1 direction → outputs");
        let _ = i2c.write(0x58u8, &[0x13u8, 0xFFu8]); // LED mode = GPIO
        let _ = i2c.write(0x58u8, &[0x05u8, 0x00u8]); // Direction = output
    }

    // Read current P0 and P1 output states
    let mut p0_val = [0u8; 1];
    let mut p1_val = [0u8; 1];
    let _ = i2c.write_read(0x58u8, &[0x02u8], &mut p0_val);
    let _ = i2c.write_read(0x58u8, &[0x03u8], &mut p1_val);
    let p0 = p0_val[0];
    let p1 = p1_val[0];
    log!("   Before reset: P0=0x{:02x} P1=0x{:02x} (P0.4={} P1.0={})",
        p0, p1, (p0 >> 4) & 1, p1 & 1);

    // Step 1: Assert PWDN HIGH (P0.4 = 1) — camera powered down
    let p0_pwdn_hi = (p0 | 0x10) & !0x00; // Keep other bits, set P0.4
    let _ = i2c.write(0x58u8, &[0x02u8, p0_pwdn_hi]);
    delay.delay_millis(10);

    // Step 2: Assert RST LOW (P1.0 = 0) — camera in reset
    let p1_rst_lo = p1 & !0x01;
    let _ = i2c.write(0x58u8, &[0x03u8, p1_rst_lo]);
    delay.delay_millis(10);

    // Step 3: Deassert PWDN LOW (P0.4 = 0) — camera powered up
    let p0_pwdn_lo = p0_pwdn_hi & !0x10;
    let _ = i2c.write(0x58u8, &[0x02u8, p0_pwdn_lo]);
    delay.delay_millis(20); // Wait for power stabilization

    // Step 4: Deassert RST HIGH (P1.0 = 1) — camera runs
    let p1_rst_hi = p1_rst_lo | 0x01;
    let _ = i2c.write(0x58u8, &[0x03u8, p1_rst_hi]);
    delay.delay_millis(30); // GC0308 needs ~20ms after reset

    // Readback verification
    let _ = i2c.write_read(0x58u8, &[0x02u8], &mut p0_val);
    let _ = i2c.write_read(0x58u8, &[0x03u8], &mut p1_val);
    log!("   After reset: P0=0x{:02x} P1=0x{:02x} (PWDN={} RST={})",
        p0_val[0], p1_val[0], (p0_val[0] >> 4) & 1, p1_val[0] & 1);
}

// ═══════════════════════════════════════════════════════════════
// GC0308 Initialization
// ═══════════════════════════════════════════════════════════════

/// Detect the GC0308 camera on I2C bus.
/// Returns true if chip ID = 0x9B.
pub fn detect_gc0308<I2C: embedded_hal::i2c::I2c>(i2c: &mut I2C) -> bool {
    // Select page 0
    sccb_write(i2c, REG_PAGE_SELECT, 0x00);
    if let Some(id) = sccb_read(i2c, REG_CHIP_ID) {
        id == GC0308_CHIP_ID
    } else {
        false
    }
}

/// Initialize the GC0308 camera for QVGA (320x240) grayscale output.
///
/// Steps:
///   1. Hardware reset via AW9523B
///   2. Write default register table
///   3. Configure subsample mode for QVGA
///   4. Set output format to Y-only (grayscale 8-bit)
///
/// Returns Ok(()) if init succeeds, Err(msg) otherwise.
pub fn init_gc0308<I2C: embedded_hal::i2c::I2c>(
    i2c: &mut I2C,
    delay: &mut Delay,
) -> Result<(), &'static str> {
    // Step 1: Full camera power-on sequence (PWDN + RST via AW9523B)
    camera_power_on(i2c, delay);
    delay.delay_millis(20);

    // Step 1b: Generate XCLK on GPIO2 using LEDC timer
    // The GC0308 needs MCLK/XCLK from the ESP32-S3 to run its pixel pipeline.
    // Without XCLK, I2C works but the sensor outputs frozen data.
    // ESP32-S3 LEDC base = 0x6001_4000 (LOW SPEED only, unlike ESP32)
    unsafe {
        // Enable LEDC peripheral clock
        // SYSTEM_PERIP_CLK_EN0_REG: bit 11 = LEDC
        let perip_clk_en0 = 0x600C_0018u32 as *mut u32;
        let clk_en = core::ptr::read_volatile(perip_clk_en0);
        core::ptr::write_volatile(perip_clk_en0, clk_en | (1u32 << 11));
        // Clear reset
        let perip_rst_en0 = 0x600C_0020u32 as *mut u32;
        let rst_en = core::ptr::read_volatile(perip_rst_en0);
        core::ptr::write_volatile(perip_rst_en0, rst_en & !(1u32 << 11));
        
        // ESP32-S3 LEDC register map (low-speed only):
        // Base = 0x6001_4000
        // LEDC_CONF_REG        = base + 0x0D0 = 0x6001_40D0
        //   bit[1:0] = LEDC_APB_CLK_SEL (1=APB 80MHz, 2=RC_FAST, 3=XTAL)
        // LEDC_TIMERx_CONF_REG = base + 0x0A0 + x*8  (timer 0 = 0x0A0)
        //   bits[3:0]  = duty_resolution
        //   bits[21:4] = clock_divider (18 bits)
        //   bit[22]    = pause
        //   bit[23]    = rst
        //   bit[24]    = tick_sel (0=APB, 1=REF_TICK) — NOT USED on S3
        //   bit[25]    = para_up (write 1 to update)
        // LEDC_CHx_CONF0_REG   = base + 0x000 + x*0x14 (ch0 = 0x000)
        //   bits[1:0]  = timer_sel
        //   bit[2]     = sig_out_en
        //   bit[3]     = idle_lv
        //   bit[4]     = para_up
        // LEDC_CHx_HPOINT_REG  = base + 0x004 + x*0x14
        // LEDC_CHx_DUTY_REG    = base + 0x008 + x*0x14
        // LEDC_CHx_CONF1_REG   = base + 0x00C + x*0x14
        //   bit[31]    = duty_start
        
        let ledc_base = 0x6001_4000u32;
        
        // Clock config: use APB (80MHz)
        let ledc_conf = (ledc_base + 0x0D0) as *mut u32;
        core::ptr::write_volatile(ledc_conf, 1u32); // APB_CLK_SEL=1 (80MHz)
        
        // Timer 0: 80MHz, 1-bit resolution, divider=2 → 80/(2*2^1) = 20MHz
        // Or for 10MHz: divider=4 → 80/(4*2^1) = 10MHz
        let timer0_conf = (ledc_base + 0x0A0) as *mut u32;
        // duty_res=1 (bits 3:0), div=2 (bits 21:4), rst=1 (bit 23)
        let timer_val_rst = (1u32) | (2u32 << 4) | (1u32 << 23);
        core::ptr::write_volatile(timer0_conf, timer_val_rst);
        // Clear reset, set para_up
        let timer_val_run = (1u32) | (2u32 << 4) | (1u32 << 25);
        core::ptr::write_volatile(timer0_conf, timer_val_run);
        
        // Channel 0: hpoint=0, duty=1 (50% for 1-bit), timer_sel=0
        let ch0_hpoint = (ledc_base + 0x004) as *mut u32;
        core::ptr::write_volatile(ch0_hpoint, 0u32);
        
        let ch0_duty = (ledc_base + 0x008) as *mut u32;
        core::ptr::write_volatile(ch0_duty, 1u32 << 4); // duty=1 left-shifted by 4
        
        let ch0_conf1 = (ledc_base + 0x00C) as *mut u32;
        core::ptr::write_volatile(ch0_conf1, 1u32 << 31); // duty_start=1
        
        let ch0_conf0 = (ledc_base + 0x000) as *mut u32;
        // timer_sel=0, sig_out_en=1, para_up=1
        core::ptr::write_volatile(ch0_conf0, (1u32 << 2) | (1u32 << 4));
        
        // Route LEDC_LS_SIG_OUT0 (signal 79) to GPIO2
        let func_out_cfg_base = 0x6000_4554u32;
        let gpio2_out_cfg = (func_out_cfg_base + 2 * 4) as *mut u32;
        core::ptr::write_volatile(gpio2_out_cfg, 79u32);
        
        // Enable GPIO2 as output
        let gpio_enable_addr = 0x6000_4020u32 as *mut u32;
        let gpio_en = core::ptr::read_volatile(gpio_enable_addr);
        core::ptr::write_volatile(gpio_enable_addr, gpio_en | (1u32 << 2));
        
        // IO_MUX GPIO2: set to GPIO function (MCU_SEL=1)
        let iomux_gpio2 = (0x6000_9000u32 + 0x04 + 2 * 4) as *mut u32;
        let mux_val = core::ptr::read_volatile(iomux_gpio2);
        core::ptr::write_volatile(iomux_gpio2, (mux_val & !0x7000) | 0x1000);
        
        // Verify: check if GPIO2 toggles
        let in0 = 0x6000_403Cu32 as *const u32;
        let mut tog = 0u32;
        let mut last = (core::ptr::read_volatile(in0) >> 2) & 1;
        for _ in 0..10_000u32 {
            let c = (core::ptr::read_volatile(in0) >> 2) & 1;
            if c != last { tog += 1; last = c; }
        }
        log!("   LEDC XCLK on GPIO2: {} toggles/10k (expect >100)", tog);
    }
    delay.delay_millis(10); // Let XCLK stabilize

    // Step 2: Check chip ID
    if !detect_gc0308(i2c) {
        return Err("GC0308 not detected (chip ID != 0x9B)");
    }

    // Step 3: Write default register table
    for &(reg, val) in GC0308_DEFAULTS.iter() {
        if !sccb_write(i2c, reg, val) {
            return Err("SCCB write failed during defaults");
        }
        // Soft reset needs extra delay
        if reg == 0xfe && val == 0x80 {
            delay.delay_millis(20);
        }
    }
    delay.delay_millis(80); // Allow camera to stabilize

    // QVGA subsample + Y-only output:
    // Subsample gives 320×240 progressive (no interlacing).
    // Y-only (0x24=0x11) gives 1 byte/pixel = 76,800 bytes/frame.
    // This is the proven V96 baseline with halved data rate.
    
    // Enable subsample on Page 1
    sccb_write(i2c, 0xfe, 0x01); // Page 1
    let r53 = sccb_read(i2c, 0x53).unwrap_or(0x00);
    sccb_write(i2c, 0x53, r53 | 0x80); // SUBSAMPLE_EN: bit 7 = 1
    let r55 = sccb_read(i2c, 0x55).unwrap_or(0x00);
    sccb_write(i2c, 0x55, r55 | 0x01); // SUBSAMPLE_EN2: bit 0 = 1
    sccb_write(i2c, 0xfe, 0x00); // Back to Page 0

    // Write subsample config registers (mode, window, etc.)
    for &(reg, val) in GC0308_SUBSAMPLE_QVGA.iter() {
        if !sccb_write(i2c, reg, val) {
            return Err("SCCB write failed during subsample config");
        }
    }

    // Disable crop (subsample handles size reduction)
    sccb_write(i2c, 0x46, 0x00);
    
    delay.delay_millis(100); // Let AEC run a few frames

    // Verify critical registers readback
    let out_en_rb = sccb_read(i2c, REG_OUTPUT_EN).unwrap_or(0xEE);
    let debug_rb = sccb_read(i2c, 0x2e).unwrap_or(0xEE);
    let fmt_rb = sccb_read(i2c, REG_OUTPUT_FORMAT).unwrap_or(0xEE);
    let sync_rb = sccb_read(i2c, 0x26).unwrap_or(0xEE);
    let drv_rb = sccb_read(i2c, 0x1f).unwrap_or(0xEE);
    let mode2_rb = sccb_read(i2c, 0x15).unwrap_or(0xEE);
    let aec_rb = sccb_read(i2c, 0xd0).unwrap_or(0xEE);
    log!("   GC0308 verify: out_en=0x{:02x} debug=0x{:02x} fmt=0x{:02x} sync=0x{:02x} drv=0x{:02x} mode2=0x{:02x} aec=0x{:02x}",
        out_en_rb, debug_rb, fmt_rb, sync_rb, drv_rb, mode2_rb, aec_rb);

    // Verify subsample is disabled
    sccb_write(i2c, 0xfe, 0x01);
    let sub53 = sccb_read(i2c, 0x53).unwrap_or(0xEE);
    let sub54 = sccb_read(i2c, 0x54).unwrap_or(0xEE);
    sccb_write(i2c, 0xfe, 0x00);
    let crop46 = sccb_read(i2c, 0x46).unwrap_or(0xEE);
    log!("   Subsample: P1:0x53=0x{:02x}(expect bit7=0) P1:0x54=0x{:02x}(expect 0x00) crop=0x{:02x}",
        sub53, sub54, crop46);
    log!("   Output format: 0x{:02x} (expect 0x11=Y-only)", fmt_rb);

    Ok(())
}

/// Re-initialize the GC0308 after XCLK is running.
/// Performs soft-reset + full register rewrite.
/// Call this after MCLK/XCLK has been established on GPIO2.
pub fn reinit_gc0308<I2C: embedded_hal::i2c::I2c>(
    i2c: &mut I2C,
    delay: &mut Delay,
) -> Result<(), &'static str> {
    log!("   Re-init GC0308 (QVGA 320x240 Y-only)...");
    
    // Soft reset
    if !sccb_write(i2c, 0xfe, 0x80) {
        return Err("Soft reset write failed");
    }
    delay.delay_millis(30);
    
    // Select page 0
    sccb_write(i2c, 0xfe, 0x00);
    delay.delay_millis(5);
    
    // Verify chip still responds
    if !detect_gc0308(i2c) {
        return Err("GC0308 not detected after soft-reset");
    }
    
    // Write the full Espressif defaults table
    for &(reg, val) in GC0308_DEFAULTS.iter() {
        if !sccb_write(i2c, reg, val) {
            return Err("SCCB write failed during reinit");
        }
        if reg == 0xfe && val == 0x80 {
            delay.delay_millis(20);
        }
    }
    delay.delay_millis(80);
    
    // QVGA subsample + Y-only output (same as init)
    sccb_write(i2c, 0xfe, 0x01); // Page 1
    let r53 = sccb_read(i2c, 0x53).unwrap_or(0x00);
    sccb_write(i2c, 0x53, r53 | 0x80); // SUBSAMPLE_EN: bit 7
    let r55 = sccb_read(i2c, 0x55).unwrap_or(0x00);
    sccb_write(i2c, 0x55, r55 | 0x01); // SUBSAMPLE_EN2: bit 0
    sccb_write(i2c, 0xfe, 0x00);

    for &(reg, val) in GC0308_SUBSAMPLE_QVGA.iter() {
        if !sccb_write(i2c, reg, val) {
            return Err("SCCB write failed during subsample config");
        }
    }

    // Force Y-only output after subsample (defaults may have reset it)
    sccb_write(i2c, 0x24, 0x91); // Y-only, ISP high 8
    sccb_write(i2c, 0x46, 0x00); // Crop off

    delay.delay_millis(100); // Let AEC run a few frames
    
    // Dump key registers to verify
    let dbg = sccb_read(i2c, 0x2e).unwrap_or(0xff);
    let exp_h = sccb_read(i2c, 0x03).unwrap_or(0);
    let exp_l = sccb_read(i2c, 0x04).unwrap_or(0);
    let gain = sccb_read(i2c, 0x50).unwrap_or(0);
    let aaaa = sccb_read(i2c, 0x22).unwrap_or(0xff);
    let r15 = sccb_read(i2c, 0x15).unwrap_or(0xff);
    let r46 = sccb_read(i2c, 0x46).unwrap_or(0xff);
    log!("   Reinit done: dbg=0x{:02x} exp=0x{:02x}{:02x} gain=0x{:02x} aaaa=0x{:02x}", 
        dbg, exp_h, exp_l, gain, aaaa);
    log!("   mode2(0x15)=0x{:02x} crop(0x46)=0x{:02x} (expect 0x0a, 0x00)",
        r15, r46);
    
    // Verify subsample is DISABLED on Page 1
    sccb_write(i2c, 0xfe, 0x01);
    let sub_en = sccb_read(i2c, 0x53).unwrap_or(0xff);
    let sub_en2 = sccb_read(i2c, 0x55).unwrap_or(0xff);
    let sub_mode = sccb_read(i2c, 0x54).unwrap_or(0xff);
    sccb_write(i2c, 0xfe, 0x00);
    let fmt = sccb_read(i2c, 0x24).unwrap_or(0xff);
    log!("   Subsample: en=0x{:02x}(bit7={}) en2=0x{:02x}(bit0={}) mode=0x{:02x} fmt=0x{:02x}",
        sub_en, (sub_en >> 7) & 1, sub_en2, sub_en2 & 1, sub_mode, fmt);
    
    Ok(())
}

/// Read a GC0308 register (for debugging)
pub fn read_reg<I2C: embedded_hal::i2c::I2c>(i2c: &mut I2C, reg: u8) -> Option<u8> {
    sccb_read(i2c, reg)
}

// ═══════════════════════════════════════════════════════════════
// Frame Constants
// ═══════════════════════════════════════════════════════════════

/// Frame dimensions for QVGA Y-only grayscale
pub const FRAME_WIDTH: usize = 320;
pub const FRAME_HEIGHT: usize = 240;
pub const FRAME_SIZE: usize = FRAME_WIDTH * FRAME_HEIGHT;

// ═══════════════════════════════════════════════════════════════
// Camera Status
// ═══════════════════════════════════════════════════════════════

/// Camera initialization status
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CameraStatus {
    /// Not initialized
    NotReady,
    /// GC0308 detected and configured via SCCB
    SensorReady,
    /// DVP capture active (LCD_CAM + DMA running)
    Capturing,
    /// Continuous bit-bang streaming mode
    Streaming,
    /// Error during init
    Error,
}

// ═══════════════════════════════════════════════════════════════
// LCD_CAM DVP peripheral initialization
// ═══════════════════════════════════════════════════════════════

/// Enable LCD_CAM system clock, configure XCLK output on GPIO2 (~10MHz).
///
/// Must be called BEFORE `LcdCam::new()` so that register writes stick.
/// Sets up:
///   - SYSTEM.PERIP_CLK_EN1 — LCD_CAM peripheral clock
///   - LCD_CLOCK_REG — lcd_clk_en, clk_sel=PLL160M, div=2
///   - CAM_CTRL_REG — cam_clk_sel=PLL160M, div=16 → 10MHz XCLK
///   - GPIO matrix — route CAM_CLK (signal 149) → GPIO2
pub fn enable_lcd_cam_clocks() {
    unsafe {
        // Enable LCD_CAM peripheral clock + reset cycle
        let clk_en1_addr = 0x600C_001Cu32 as *mut u32;
        let rst_en1_addr = 0x600C_0024u32 as *mut u32;
        let clk_en1 = core::ptr::read_volatile(clk_en1_addr);
        if clk_en1 & 1 == 0 {
            core::ptr::write_volatile(clk_en1_addr, clk_en1 | 1);
            let rst = core::ptr::read_volatile(rst_en1_addr);
            core::ptr::write_volatile(rst_en1_addr, rst | 1);
            for _ in 0..100u32 { core::ptr::read_volatile(&0u32); }
            core::ptr::write_volatile(rst_en1_addr, rst & !1u32);
            for _ in 0..100u32 { core::ptr::read_volatile(&0u32); }
        }

        // Enable lcd_clk_en (bit 31) + clk_sel=PLL160M (bits 30:29=2) + div=2 (bits 15:8)
        let lcd_clock_addr = 0x6004_1000u32 as *mut u32;
        let lcd_clk = core::ptr::read_volatile(lcd_clock_addr);
        if lcd_clk & (1u32 << 31) == 0 {
            let lcd_clock_val = (1u32 << 31) | (2u32 << 29) | (2u32 << 8);
            core::ptr::write_volatile(lcd_clock_addr, lcd_clock_val);
        }

        // Configure CAM_CTRL: clk_sel=PLL160M, div_num=16 → 10MHz XCLK
        let cam_ctrl_addr = 0x6004_1004u32 as *mut u32;
        let cam_ctrl_pre = core::ptr::read_volatile(cam_ctrl_addr);
        let mut cam_ctrl_val = cam_ctrl_pre;
        cam_ctrl_val &= !(0xFF | (0xFF << 8) | (3 << 16) | (3 << 18));
        cam_ctrl_val |= 16;        // div_num = 16
        cam_ctrl_val |= 2 << 18;   // clk_sel = 2 (PLL160M)
        core::ptr::write_volatile(cam_ctrl_addr, cam_ctrl_val);

        // Route CAM_CLK (signal 149) → GPIO2
        let func_out_cfg_base = 0x6000_4554u32;
        let gpio2_out_cfg = (func_out_cfg_base + 2 * 4) as *mut u32;
        core::ptr::write_volatile(gpio2_out_cfg, 149u32);
        // Enable GPIO2 output
        let gpio_en0 = 0x6000_4020u32 as *mut u32;
        let en = core::ptr::read_volatile(gpio_en0);
        core::ptr::write_volatile(gpio_en0, en | (1u32 << 2));
        // IO_MUX GPIO2 → GPIO function (MCU_SEL=1)
        let iomux_gpio2 = (0x6000_9000u32 + 0x04 + 2 * 4) as *mut u32;
        let mux_val = core::ptr::read_volatile(iomux_gpio2);
        core::ptr::write_volatile(iomux_gpio2, (mux_val & !0x7000) | 0x1000);
    }
}

/// Ensure LCD_CLOCK.CLK_EN is set. Call right before `Camera::new()`.
pub fn ensure_lcd_clk_enabled() {
    unsafe {
        let lcd_clk = core::ptr::read_volatile(0x6004_1000u32 as *const u32);
        if lcd_clk & (1u32 << 31) == 0 {
            core::ptr::write_volatile(0x6004_1000u32 as *mut u32, lcd_clk | (1u32 << 31));
        }
    }
}

/// Verify XCLK is toggling on GPIO2. Returns number of edges detected in ~10k samples.
/// A value >100 means XCLK is running.
pub fn verify_xclk_running() -> u32 {
    unsafe {
        let in0 = 0x6000_403Cu32 as *const u32;
        let mut tog = 0u32;
        let mut last = (core::ptr::read_volatile(in0) >> 2) & 1;
        for _ in 0..10_000u32 {
            let c = (core::ptr::read_volatile(in0) >> 2) & 1;
            if c != last { tog += 1; last = c; }
        }
        tog
    }
}

/// Configure GPIO matrix routing for all DVP camera signals.
///
/// Maps physical GPIO pins to LCD_CAM input signals via func_in_sel_cfg.
/// Also enables input buffers on all camera pins via IO_MUX.
///
/// Pin map (M5Stack CoreS3):
///   PCLK=GPIO45, VSYNC=GPIO46, HREF=GPIO38
///   D0=39, D1=40, D2=41, D3=42, D4=15, D5=16, D6=48, D7=47
pub fn setup_cam_gpio_routing() {
    unsafe {
        let gpio = &*esp_hal::peripherals::GPIO::PTR;
        let io_mux = &*esp_hal::peripherals::IO_MUX::PTR;

        // Enable input buffer + GPIO function on all camera pins
        let cam_gpios: [u8; 11] = [45, 46, 38, 39, 40, 41, 42, 15, 16, 47, 48];
        for &pin in &cam_gpios {
            io_mux.gpio(pin as usize).modify(|_, w| {
                w.fun_ie().set_bit();
                w.mcu_sel().bits(1)
            });
        }

        // Route GPIO → LCD_CAM input signal via GPIO matrix
        let route = |signal_idx: usize, gpio_num: u8| {
            gpio.func_in_sel_cfg(signal_idx).write(|w| {
                w.bits(0x80 | gpio_num as u32)
            });
        };

        route(149, 45);  // CAM_PCLK_IDX ← GPIO45
        route(152, 46);  // CAM_V_SYNC_IDX ← GPIO46
        gpio.func_in_sel_cfg(151).write(|w| w.bits(0x80 | 0x3C)); // CAM_H_SYNC ← const 1
        route(150, 38);  // CAM_H_ENABLE_IDX ← GPIO38 (HREF)
        // CAM_DATA_IN0..7 = signals 133..140
        route(133, 39);  route(134, 40);  route(135, 41);  route(136, 42);
        route(137, 15);  route(138, 16);  route(139, 48);  route(140, 47);
    }
}

/// Configure LCD_CAM for VSYNC-based EOF and HREF data gating.
///
/// Sets cam_vs_eof_en=1 and cam_vh_de_mode_en=1 in CAM_CTRL / CAM_CTRL1.
pub fn configure_cam_vsync_eof() {
    unsafe {
        let cam_ctrl_addr = 0x6004_1004u32 as *mut u32;
        let cam_ctrl1_addr = 0x6004_1008u32 as *mut u32;
        let cur = core::ptr::read_volatile(cam_ctrl_addr);
        core::ptr::write_volatile(cam_ctrl_addr, cur | (1u32 << 22) | (1u32 << 31));
        let cur1 = core::ptr::read_volatile(cam_ctrl1_addr);
        core::ptr::write_volatile(cam_ctrl1_addr, cur1 | 1u32);
    }
}
